name: Deploy Website

on:
  push:
    branches:
      - development  # Atur branch yang akan memicu action ini, misalnya 'main' atau 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    #- name: Install dependencies
    #  run: npm install # Jika menggunakan npm, sesuaikan jika kamu menggunakan yarn atau lainnya

    #- name: Build the website
     # run: npm run build # Sesuaikan dengan perintah build proyek kamu

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        #publish_dir: ./dist # Sesuaikan dengan folder build hasil proyek kamu
