# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Deploy to gh-pages

on:
  push:
    branches:
      - development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository 
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Configure Node.js environment and install dependencies
      - name: Set up Node.js and install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '23'
      
      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests (optional)
      - name: Run tests
        run: npm test

      # Step 5: Build the app
      - name: Build the app
        run: npm run build

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
